import 'package:get/get.dart';

class Languages extends Translations {
  @override
  Map<String, Map<String, String>> get keys {
    return {
      "en_US": {
        "Sorry_for_the_technical_Beakdown" :
        "Sorry for the technical Breakdown issue. We are here to help you. please wait while we resolve.",
        "payment_back":"Your transaction is under process , Are you sure you want to close this tab?",
        "Dont_have": "Don’t have an account yet?",
        "language": "English",
        "forgot_password": "Forgot Password",
        "otp": "OTP",
        "new_password": "New Password",
        "confirm_new_password": "Confirm New Password",
        "submit": "Submit",
        "please_enter_otp": "Please enter OTP",
        "wrong_otp": "Wrong OTP",
        "please_enter_password": "Please enter password",
        "password_length": "Password length must be between 6–15 characters.",
        "password_should_be_same": "Password should be same",
        "welcome_back": "Welcome back",
        "email": "Email",
        "password": "Password",
        "log_in": "Log In",
        "don't_have_an_account?": "Don't have an account?",
        "register": "Register",
        "verification_code": "Verification Code",
        "You_deserve_the_best_Connecting_you_with_the_best_driver":
            "You deserve the best, Connecting you with the best driver",
        "continue": "Continue",
        "please_enter_valid_otp": "Please enter valid otp",
        "didn_t_get_the_OTP": "didn`t Get The OTP?",
        "resend_OTP": "RESEND OTP ",
        "enter_phone": "Enter phone number to continue",
        "phone": "Phone",
        "Please_type_the_verification_code_sent_to_your":
            "Please type the verification code sent to your",
        "mobile_number": " Mobile Number",
        "Please_type_the_verification_code_sent_to_your_email":
            "Please type the verification code sent to your Email",
        "please_number.": "Please enter your mobile number.",
        "check_fare": "Check Fare",
        "sign_up": "Sign Up",
        "Or_continue_with": "Or Continue with",
        "create_account": "Create\nAccount",
        "first_name": "First Name",
        "last_name": "Last Name",
        "confirm_password": "Confirm Password",
        "i_have_read": "I have read and agreed the Terms and\nConditions.",
        "terms_condition": "Terms Conditions",
        "sign_in": "Sign In",
        "Don't-have_account?": "Don't have an account?",
        "are_sure_delete?": "Are sure you want to delete?",
        "no": "NO",
        "delete": "DELETE",
        "no_data_found..": "No data found..",
        "valid_till": "Valid Till",
        "remove": "Remove",
        "use_code": "Use Code",
        "dispute": "Dispute",
        "you": "You",
        "admin": "Admin",
        "driver_unprofessional": "Driver Unprofessional",
        "something_went_wrong...": "Something went wrong...",
        "please_dispute..": "Please select any dispute..",
        "dismiss": "Dismiss",
        "finding_driver...": "Finding driver...",
        "cancel_request": "Cancel Request",
        "invoice": "Invoice",
        "booking_id": "Booking ID",
        "time-Taken": "Time Taken",
        "base_fare": "Base Fare",
        "time_fare": "Time Fare",
        "distance_fare": "Distance Fare",
        "waiting_amount": "Waiting Amount",
        "toll_charges": "Toll Charges",
        "tips": "Tips",
        "add_tip": "Add Tip",
        "total": "Total",
        "wallet_detection": "Wallet Detection",
        "round_off": "Round Off",
        "discount": "Discount",
        "payable": "Payable",
        "payment_:_": "Payment : ",
        "change": "CHANGE",
        "payment_driver": "Payment not confirmed from the driver",
        "done": "Done",
        "pay_now": "Pay now",
        "lost_item": "Lost Item",
        "Mention_the_lost_item": "Mention the lost item",
        "please_details": "Please enter lost item details",
        "ratings_your_trip_with": "Ratings your trip with",
        "write_your_comment": "Write your comment",
        "reason_for_canceling": "Reason for canceling",
        "scan_the_number": "Scan the QR to fetch mobile number",
        "sos_alert": "SOS Alert",
        "are_you_sure_alert?":
            "Are you sure you want to proceed with emergency alert?",
        "yes": "YES",
        "time_taken": "Time Taken",
        "tax": "Tax",
        "close": "Close",
        "help": "Help",
        "support": "Support",
        "call": "Call",
        "message": "Message",
        "our_you_soon!": "Our team persons will contact you soon!",
        "invite_friend": "Invite Friend",
        "your_referral_code": "Your Referral Code",
        "choose_one": "choose one",
        "referral_count :": "Referral Count :",
        "referral_amount:": "Referral Amount:",
        "notification_manager": "Notification Manager",
        "you_any_notification": "You don't have any notification",
        "passbook": "Passbook",
        "no_wallet_history": "No Wallet History",
        "amount": "Amount",
        "balance": "Balance : ",
        "lost_my_item": "Lost my item",
        "past_trip_details": "Past Trip Details",
        "where_do_you_need_the_mechanic": "Where do you need the Mechanic?",
        "pay_via": "Pay via",
        "comments": "Comments",
        "no_comments": "No Comments",
        "view_receipt": "View Receipt",
        "open": "OPEN",
        "payment_options": "Payment Options",
        "cash": "Cash",
        "by_cash": "By Cash",
        "card": "Card",
        "add": "Add",
        "payStack": "PayStack",
        "profile": "Profile",
        "phone_number": "Phone Number",
        "looking_to_change_password": "Looking to change password",
        "save": "Save",
        "setting": "Setting",
        "favorites": "Favorites",
        "home": "Home",
        "work": "Work",
        "choose_language": "Choose Language",
        "upcoming_trip_details": "Upcoming Trip Details",
        "cancel_ride": "Cancel Ride",
        "wallet": "Wallet",
        "your_wallet_amount": "Your Wallet Amount",
        "add_money": "Add Money",
        "add_amount": "Add Amount",
        "please_enter_amount": "Please enter amount",
        "Please_enter_more_when_amount": "Please enter more then 0 amount",
        "your_trips": "Your Trips",
        "no_past_Trips_found": "No Past Trips found",
        "no_upcoming_trips_found": "No upcoming trips found",
        "cancel": "Cancel",
        "add_card_for_payments": "Add card for payments",
        "card_number": "Card Number",
        "expiration_date": "Expiration Date",
        "add_card": "Add Card",
        "please_insert_valid_expiry_date": "Please insert valid expiry date",
        "change_password": "Change\nPassword",
        "current_password": "Current Password",
        "chat": "Chat",
        "loading...": "Loading...",
        "type_something_here": "Type Something Here",
        "from_to": "Enter pickup location",
        "enter_destination": "Enter destination",
        "where_to?": "Where To?",
        "apply_coupon": "Apply Coupon",
        "view_code": "View Code",
        "request": "Request",
        "rate_card": "Rate Card",
        "fare /": "Fare /",
        "fare_type": "Fare Type",
        "capacity": "Capacity",
        "schedule_a_ride": "Schedule a ride",
        "choose_a_date": "Choose a date",
        "please_select_date": "Please Select date",
        "please_select_time": "Please Select time",
        "sos": "SOS",
        "otp:": "OTP: ",
        "cancel_trip": "Cancel Trip",
        "eta": "ETA",
        "share_status": "Share Status",
        "location_permissions_are_denied": "Location permissions are denied",
        "allow": "Allow",
        "kms": "Kms",
        "where_to": "Where To",
        "pick_from_map": "Pick from map",
        "round_trip": "Round Trip",
        "location_permissions_denied": "Location permissions are denied",
        "payment": "Payment",
        "apply_coupan": "Apply Cupon",
        "cpD01": "CPD01",
        "10%_Off_Max_50": "10% Off Max discount is 50",
        "valid_Till_13,June_2021": "valid Till : 13,June 2021",
        "view_Code": "View Code",
        "case": "Cash",
        "location_denied": "Location permissions are denied",
        "payments": "Payments",
        "offer": "Offer",
        "settings": "Settings",
        "notification_manger": "Notification Manger",
        "share": "Share",
        "invite_Friend": "Invite Friend",
        "logout": "Logout",
        "choose_onew": "Choose one",
        "hey_User": "Hey Checkout this app, Rekoverme",
        "use_wallet": "Use Wallet",
        "past_rides": "Past requests",
        "account": "Account",
        "where_would-you_like_to_go?": "Where would you like to go?",
        "other": "Other",
        "where_is_your_destination": "Where is your destination ?",
        "past": "Past",
        "upcoming": "Upcoming",
        "eto_credit_balance": "Arby Credit Balance",
        "saved_addresses": "Saved Addresses",
        "saved_contacts": "Saved Contacts",
        "change_language": "Change language",
        "hindi": "Hindi",
        "De:": "De:",
        "A:": "A:",
        "home_destination_is_not_added": "Home destination is not added",
        "work_destination_is_not_added": "Work destination is not added",
        "address_is_not_added": "Address is not added",
        "recent_locations": "Recent locations",
        "trip_details": "Service Details",
        "source": "Source",
        "destination": "Destination",
        "select_car": "Select Car",
        "myself": "MySelf",
        "coupons": "Coupons",
        "driver_is_arriving...": "Driver is arriving",
        "driver_has_arrived.": "Driver has Arrived.",
        "your_ride_has_started": "Your ride has started",
        "arrival": "Arrival",
        "rate_driver": "Rate Driver",
        "someone_else_taking_the_ride?": "Someone else taking the ride?",
        "choose a contact so that they also get driver number, vehicle details and ride OTP via SMS":
            "Choose a contact so that they also get driver number, vehicle details and ride OTP via SMS",
        "book_for_someone": "Book for someone",
        "book_for_someone_else": "Book for someone else",
        "payment_methods": "Payment Methods",
        "online(UPI, Card, Net banking)": "Online(UPI, Card, Net banking)",
        "how_is_your_driver?": "How is your driver?",
        "please_rate_your_driver": "Please rate your driver",
        "feedback_for_the_driver": "Feedback for the driver",
        "delete_account": "Delete\nAccount",
        "pick_contact": "Pick Contact",
        "save_contact": "Save Contact",
        "together_we are": "Together, we\'re growing\nStronger and further",
        "refer_now_and_earn": "Refer now amd earn",
        "referral_code": "Referral code",
        "or": "Or",
        "share_your_link_via": "Share your link via",
        "spread the word, And we will reward you":
            "Spread the word, And we will reward you",
        "get INR 100 in your Eto wallet for every friend you refer":
            "Get INR 100 in your Arby wallet for every friend you refer",
        "referral Count": "Referral Count",
        "Referral Amount": "Referral Amount",
        "Tell_us_your_experience_with_ETO": "Tell us your experience with Arby",
        "hi": "Hi, ",
        "Write_something": "Write something.....",
        "Skip": "Skip",
        "No": "No",
        "Yes": "Yes",


        "where_to_go":"Where to go ?",
        "detail_ride":"Detail Ride",
        "Panic_button":"Panic button S.O.S",
        "leave_a_feedback":"Leave a Feedback",
        "Search_a_driver_nice":"Search a driver NICE !",
        "seg":"Seg.",
        "You_are_now_riding_for_a_good_causes":"You are now riding foa a good causes -1% of the Arby revenue goes treatment of cancer patients.",
      },
      "hi_IN": {
        "Sorry_for_the_technical_Beakdown" :
        "तकनीकी खराबी की समस्या के लिए क्षमा करें। हम यहां आपकी सहायता के लिए उपलब्ध हैं। जब तक हम समाधान करते हैं कृपया प्रतीक्षा करें।",
    "No": "नहीं",
    "Yes": "हां",
        "payment_back":"आपका लेन-देन प्रक्रियाधीन है, क्या आप सुनिश्चित हैं कि आप इस टैब को बंद करना चाहते हैं?",
        "Skip": "छोड़ें",
        "Tell_us_your_experience_with_ETO": "ईटीओ के साथ अपना अनुभव हमें बताएं",
        "Write_something": "कुछ लिखेंगे.....",
        "You_deserve_the_best_Connecting_you_with_the_best_driver":
            "आप सबसे अच्छे के लायक हैं, आपको सबसे अच्छे ड्राइवर से जोड़ते हैं",
        "Dont_have": "अब तक कोई खाता नहीं है?",
        "language": "हिन्दी",
        "forgot_password": " पासवर्ड भूल गए ",
        "where_do_you_need_the_mechanic": "आपको मैकेनिक की आवश्यकता कहां है?",
        "otp": " ओटीपी ",
        "verification_code": "पुष्टि संख्या",
        "new_password": " नया पासवर्ड ",
        "confirm_new_password": " नए पासवर्ड की पुष्टि करें ",
        "submit": " प्रस्तुत करना ",
        "Please_type_the_verification_code_sent_to_your":
            "कृपया आपके पर भेजा गया सत्यापन कोड टाइप करें",
        "mobile_number": "मोबाइल नंबर",
        "Please_type_the_verification_code_sent_to_your_email":
            "कृपया आपके ईमेल पर भेजा गया सत्यापन कोड टाइप करें",
        "please_enter_otp": " कृपया ओटीपी दर्ज करें ",
        "wrong_otp": " गलत ओटीपी ",
        "please_enter_password": " कृप्या पास्वर्ड भरो ",
        "password_length": " पासवर्ड की लंबाई 6-15 अक्षरों के बीच होनी चाहिए.",
        "password_should_be_same": " पासवर्ड समान होना चाहिए ",
        "welcome_back": " वापसी पर स्वागत है ",
        "email": " ईमेल ",
        "password": " पासवर्ड ",
        "log_in": " लॉग इन करें ",
        "don't_have_an_account?": " खाता नहीं है?",
        "register": " पंजीकरण करवाना ",
        "Please_type_the_verification_code_sent_to_your":
            " कृपया सत्यापन कोड टाइप करें\nआपके पास भेजा गया ",
        "continue": " जारी रखना ",
        "please_enter_valid_otp": " कृपया मान्य ओटीपी दर्ज करें ",
        "didn_t_get_the_OTP": " ओटीपी नहीं मिला? ",
        "resend_OTP": " ओटीपी पुनः भेजें ",
        "enter_phone": " जारी रखने के लिए फ़ोन नंबर दर्ज करें ",
        "phone": " फ़ोन ",
        "please_number.": " अपना मोबाइल नंबर दर्ज करें.",
        "check_fare": " किराया जांचें ",
        "sign_up": " साइन अप करें ",
        "Or_continue_with": " या साथ जारी रखें ",
        "create_account": " खाता बनाएं ",
        "first_name": " पहला नाम ",
        "last_name": " उपनाम ",
        "confirm_password": " पासवर्ड की पुष्टि कीजिये ",
        "i_have_read": " मैंने नियम और शर्तें पढ़ ली हैं और उनसे सहमत हूं.",
        "terms_condition": " नियम एवं शर्तें ",
        "sign_in": " साइन इन करें ",
        "Don't-have_account?": " खाता नहीं है?",
        "are_sure_delete?": " क्या आप वाकई मिटाना चाहते हैं?",
        "no": " ना ",
        "delete": " मिटाना ",
        "no_data_found..": " कोई डेटा नहीं मिला..",
        "valid_till": " तक मान्य है ",
        "remove": " हटाना ",
        "use_code": " कोड का प्रयोग करें ",
        "dispute": " विवाद ",
        "you": " आप ",
        "admin": " व्यवस्थापक ",
        "driver_unprofessional": " चालक अव्यवसायिक ",
        "something_went_wrong...": " कुछ गलत हो गया...",
        "please_dispute..": " कृपया कोई विवाद चुनें..",
        "dismiss": " नकार देना ",
        "finding_driver...": " ड्राइवर ढूंढ रहा है...",
        "cancel_request": " अनुरोध रद्द ",
        "invoice": " इनवॉइस ",
        "booking_id": "बुकिंग आईडी ",
        "time-Taken": " समय लिया ",
        "base_fare": " बुनियादी भाड़ा",
        "time_fare": " समय किराया ",
        "distance_fare": " दूरी किराया ",
        "waiting_amount": " प्रतीक्षा राशि",
        "toll_charges": " टोल शुल्क ",
        "tips": " सलाह ",
        "add_tip": " युक्ति जोड़ें ",
        "total": " कुल ",
        "wallet_detection": " वॉलेट का पता लगाना ",
        "round_off": " पूर्णांक करना ",
        "discount": " छूट",
        "payable": " देय ",
        "payment_:_": " भुगतान : ",
        "change": " परिवर्तन ",
        "payment_driver": " ड्राइवर पार्टनर से भुगतान की पुष्टि नहीं हुई ",
        "done": " पूर्ण ",
        "pay_now": "अब भुगतान करें ",
        "lost_item": " खोई हुई वस्तु ",
        "Mention_the_lost_item": " खोई हुई वस्तु का उल्लेख करें ",
        "please_details": " कृपया खोई हुई वस्तु का विवरण दर्ज करें ",
        "ratings_your_trip_with": " के साथ अपनी यात्रा का मूल्यांकन करें ",
        "write_your_comment": " अपनी टिप्पणी लिखें ",
        "reason_for_canceling": " रद्द करने का कारण ",
        "scan_the_number":
            " मोबाइल नंबर प्राप्त करने के लिए क्यूआर स्कैन करें ",
        "sos_alert": " आपात स्थिति अलर्ट ",
        "are_you_sure_alert?":
            " क्या आप वाकई आपातकालीन चेतावनी के साथ आगे बढ़ना चाहते हैं?",
        "yes": " हां ",
        "time_taken": " समय लिया ",
        "tax": " कर ",
        "close": " बंद करना ",
        "help": "मदद",
        "support": " सहायता ",
        "call": " बुलाना ",
        "message": " संदेश ",
        "our_you_soon!": " हमारी टीम के लोग जल्द ही आपसे संपर्क करेंगे!",
        "invite_friend": "मित्र को न्योता ",
        "your_referral_code": " आपका रेफरल कोड ",
        "choose_one": " एक का चयन ",
        "referral_count :": " रेफरल काउंट:",
        "referral_amount:": " रेफरल राशि:",
        "notification_manager": " अधिसूचना प्रबंधक ",
        "you_any_notification": " आपके पास कोई सूचना नहीं है ",
        "passbook": " पासवृक ",
        "no_wallet_history": " कोई बटुआ इतिहास नहीं ",
        "amount": " राशि ",
        "balance": " संतुलन: ",
        "lost_my_item": " मेरी वस्तु खो गई ",
        "past_trip_details": " पिछली यात्रा का विवरण ",
        "pay_via": " माध्यम से भुगतान करें ",
        "comments": "टिप्पणियाँ ",
        "no_comments": " कोई टिप्पणी नहीं ",
        "view_receipt": " रसीद देखें ",
        "open": " खोलना ",
        "payment_options": " भुगतान विकल्प ",
        "cash": " नकद ",
        "by_cash": " नकद द्वारा ",
        "card": " कार्ड ",
        "add": " जोड़ें ",
        "payStack": " PayStack ",
        "profile": " प्रोफ़ाइल ",
        "phone_number": " फ़ोन नंबर ",
        "looking_to_change_password": " पासवर्ड बदलना चाह रहे हैं ",
        "save": " बचाना ",
        "setting": " स्थापना ",
        "favorites": " पसंदीदा ",
        "home": " घर ",
        "work": " काम ",
        "choose_language": "भाषा चुनें ",
        "upcoming_trip_details": " आगामी यात्रा विवरण ",
        "cancel_ride": " राइड रद्द करें ",
        "wallet": " बटुआ ",
        "your_wallet_amount": " बटुआ ",
        "add_money": " पैसे जोड़ें ",
        "add_amount": " राशि जोड़ें ",
        "please_enter_amount": " कृपया राशि दर्ज करें ",
        "Please_enter_more_when_amount": " कृपया 0 से अधिक राशि दर्ज करें ",
        "your_trips": " आपकी यात्राएं ",
        "no_past_Trips_found": " कोई पिछली यात्राएं नहीं मिलीं ",
        "no_upcoming_trips_found": " कोई आगामी ट्रिप नहीं मिली ",
        "cancel": " रद्द करना ",
        "add_card_for_payments": " भुगतान के लिए कार्ड जोड़ें ",
        "card_number": " कार्ड नंबर ",
        "expiration_date": " समाप्ति तिथि ",
        "add_card": " कार्ड जोड़ें ",
        "please_insert_valid_expiry_date": " कृपया मान्य समाप्ति तिथि डालें ",
        "change_password": " पासवर्ड\nबदलें ",
        "current_password": " वर्तमान पासवर्ड ",
        "chat": " बात करना ",
        "loading...": " लोड हो रहा है...",
        "type_something_here": " यहाँ कुछ टाइप करें ",
        "from_to": "पिकअप स्थान दर्ज करें",
        "enter_destination": "गंतव्य दर्ज करें",
        "where_to?": " जहां?",
        "apply_coupon": " कूपन लागू करें ",
        "view_code": " कोड देखें ",
        "request": "अनुरोध ",
        "rate_card": " दर कार्ड ",
        "fare /": " किराया /",
        "fare_type": " किराए का प्रकार ",
        "capacity": " क्षमता ",
        "schedule_a_ride": " राइड शेड्यूल करें ",
        "choose_a_date": " एक तिथि चुनें ",
        "please_select_date": " कृपया तिथि चुनें ",
        "please_select_time": " कृपया समय चुनें ",
        "sos": " मुसीबत का इशारा ",
        "otp:": " ओटीपी: ",
        "cancel_trip": " यात्रा रद्द करें ",
        "eta": "",
        "share_status": " शेयर स्थिति ",
        "location_permissions_are_denied": " स्थान अनुमतियां अस्वीकृत हैं ",
        "allow": " अनुमति देना ",
        "kms": " किलोमीटर ",
        "where_to": " जहां ",
        "pick_from_map": " मानचित्र से चुनें ",
        "round_trip": " राउंड ट्रिप ",
        "location_permissions_denied": " स्थान अनुमतियां अस्वीकृत हैं ",
        "payment": " भुगतान ",
        "apply_coupan": " कूपन लागू करें ",
        "cpD01": "CPD01",
        "10%_Off_Max_50": "अधिकतम छूट पर 10% की छूट 50 है",
        "valid_Till_13,June_2021": " तक वैध: 13, जून 2021",
        "view_Code": " कोड देखें ",
        "case": " नकद ",
        "location_denied": " स्थान अनुमतियां अस्वीकृत हैं ",
        "payments": " भुगतान ",
        "offer": " प्रस्ताव ",
        "settings": "समायोजन ",
        "notification_manger": "सूचना प्रबंधक ",
        "share": "शेयर करना ",
        "invite_Friend": "मित्र को न्योता ",
        "logout": "लॉग आउट ",
        "choose_onew": " एक का चयन ",
        "hey_User": " अरे इस ऐप को चेकआउट करें, Arby User ",
        "use_wallet": " वॉलेट का प्रयोग करें ",
        "hi": " नमस्ते ",
        "past_rides": "पिछले अनुरोध",
        "account": "खाता",
        "where_would-you_like_to_go?": "आप कहां जाना चाहाेगे?",
        "other": "अन्य",
        "where_is_your_destination": "आपकी मंजिल कहाँ है ?",
        "your_trips": "आपकी यात्राएं",
        "past": "अतीत",
        "upcoming": "आगामी",
        "add_amount": "राशि जोड़ें",
        "eto_credit_balance": "ईटीओ क्रेडिट बैलेंस",
        "past_rides": "पिछले अनुरोध",
        "saved_addresses": "सहेजे गए पते",
        "saved_contacts": "सहेजे गए संपर्क",
        "change_language": "भाषा बदलो",
        "hindi": "हिन्दी",
        "from:": "से:",
        "to:": "प्रति:",
        "home_destination_is_not_added": "गृह गंतव्य जोड़ा नहीं गया है",
        "work_destination_is_not_added": "कार्य गंतव्य नहीं जोड़ा गया है",
        "address_is_not_added": "पता नहीं जोड़ा गया है",
        "recent_locations": "हाल के स्थान",
        "trip_details": "सेवा विवरण",
        "source": "स्रोत",
        "destination": "गंतव्य",
        "select_car": "कार चुनें",
        "myself": "खुद",
        "coupons": "कूपन",
        "driver_is_arriving...": "ड्राइवर आ रहा है...",
        "driver_has_arrived.": "ड्राइवर आ गया है.",
        "your_ride_has_started": "आपकी सवारी शुरू हो गई है.",
        "arrival": "आगमन",
        "rate_driver": "ड्राइवर रेटिंग",
        "someone_else_taking_the_ride?": "कोई और सवारी कर रहा है?",
        "choose a contact so that they also get driver number, vehicle details and ride OTP via SMS":
            "एक संपर्क चुनें ताकि उन्हें चालक संख्या, विवरण के पीछे और एसएमएस के माध्यम से ओटीपी प्राप्त हो सके",
        "book_for_someone": "किसी के लिए बुक",
        "book_for_someone_else": "सहेजे गए संपर्क",
        "payment_methods": "भुगतान की विधि",
        "online(UPI, Card, Net banking)": "ऑनलाइन (यूपीआई, कार्ड, नेट बैंकिंग)",
        "how_is_your_driver?": "आपका ड्राइवर कैसा है?",
        "please_rate_your_driver": "कृपया अपने ड्राइवर को रेट करें",
        "feedback_for_the_driver": "ड्राइवर के लिए प्रतिक्रिया",
        "delete_account": "खाता\nहटा दो",
        "pick_contact": "संपर्क उठाओ",
        "save_contact": "संपर्क सहेज",
        "together_we are": "एक साथ, हम मजबूत\nऔर आगे बढ़ रहे हैं",
        "refer_now_and_earn": "अभी रेफर करें और कमाएं",
        "referral_code": "रेफरल कोड",
        "or": "या",
        "share_your_link_via": "के माध्यम से अपना लिंक साझा करें",
        "spread the word, And we will reward you":
            "प्रचार करें, और हम आपको पुरस्कृत करेंगे",
        "get INR 100 in your Eto wallet for every friend you refer":
            "आपके द्वारा संदर्भित प्रत्येक मित्र के लिए अपने Eto वॉलेट में INR 100 प्राप्त करें",
        "Referral Count": "रेफरल गिनती",
        "Referral Amount": "रेफरल राशि"
      },
      "nl_NL": {
        "language": "Dutch",
        "forgot_password": "Wachtwoord vergeten",
        "where_do_you_need_the_mechanic": "Waar heb je de monteur nodig?",
        "trip_details": "Servicegegevens",
        "otp": "OTP",
        "new_password": "nieuw paswoord",
        "confirm_new_password": "Bevestig nieuw wachtwoord",
        "submit": "Indienen",
        "please_enter_otp": "Voer alstublieft OTP in",
        "wrong_otp": "Verkeerde OTP",
        "please_enter_password": "Voer wachtwoord in alstublieft",
        "password_length":
            "De lengte van het wachtwoord moet tussen 6-15 tekens zijn.",
        "password_should_be_same": "Wachtwoord moet hetzelfde zijn",
        "welcome_back": "Welkom Rug",
        "email": "E-mail",
        "password": "Wachtwoord",
        "log_in": "Log In",
        "don't_have_an_account?": "Heb je geen account?",
        "register": "Register",
        "verification_code": "Verificatie code",
        "Please_type_the_verification_code_sent_to_your":
            "Typ de verificatiecode a.u.b.\nverzonden naar uw",
        "continue": "Doorgaan",
        "please_enter_valid_otp": "Vul a.u.b. geldige otp in",
        "didn`t_get_the_OTP": "heb de OTP niet gekregen",
        "resend_OTP": "RESEND OTP",
        "enter_phone": "OTP OPNIEUW VERZENDEN",
        "phone": "Telefoon",
        "please_number.": "Voer alstublieft uw mobiele nummer in.",
        "check_fare": "Controleer tarief",
        "sign_up": "Aanmelden",
        "Or_continue_with": "Of Ga verder met",
        "create_account": "Creëren\nAccount",
        "first_name": "Voornaam",
        "last_name": "Achternaam",
        "confirm_password": "bevestig wachtwoord",
        "i_have_read":
            "Ik heb de voorwaarden gelezen en ga ermee akkoord en\nConditie.",
        "terms_condition": "Algemene voorwaarden",
        "sign_in": "Log in",
        "Don't-have_account?": "Don't have an account?",
        "are_sure_delete?": "Weet je zeker dat je wilt verwijderen?",
        "no": "NEE",
        "delete": "VERWIJDEREN",
        "no_data_found..": "Geen data gevonden..",
        "valid_till": "geldig tot",
        "remove": "Verwijderen",
        "use_code": "Gebruik code",
        "dispute": "Onenigheid",
        "you": "Jij",
        "admin": "beheerder",
        "driver_unprofessional": "Bestuurder onprofessioneel",
        "something_went_wrong...": "Er is iets fout gegaan...",
        "please_dispute..": "Selecteer een geschil..",
        "dismiss": "Afwijzen",
        "finding_driver...": "Bestuurder zoeken...",
        "cancel_request": "Annuleringsaanvraag.",
        "invoice": "Factuur",
        "time-Taken": "Tijd genomen",
        "base_fare": "Basistarief",
        "time_fare": "Tijdtarief",
        "distance_fare": "Afstand tarief",
        "waiting_amount": "Wachtbedrag",
        "toll_charges": "Tolkosten",
        "tips": "Tips",
        "add_tip": "Tip toevoegen",
        "total": "Totaal",
        "wallet_detection": "Portemonnee detectie",
        "discount": "Korting",
        "payable": "te betalen",
        "payment_:_": "Betaling :",
        "change": "WIJZIGEN",
        "payment_driver": "Betaling niet bevestigd door de chauffeur",
        "done": "Gedaan",
        "pay_now": "Nu betalen",
        "lost_item": "Verloren voorwerp",
        "Mention_the_lost_item": "Vermeld het verloren voorwerp",
        "please_details": "Voer details van verloren voorwerpen in",
        "ratings_your_trip_with": "Beoordeelt uw reis met",
        "write_your_comment": "Schrijf je commentaar",
        "reason_for_canceling": "Reden van annuleren",
        "scan_the_number": "Scan de QR om het mobiele nummer op te halen",
        "sos_alert": "SOS-melding",
        "are_you_sure_alert?":
            "Weet u zeker dat u door wilt gaan met een noodwaarschuwing?",
        "yes": "JA",
        "booking_id": "Boekings-ID",
        "time_taken": "Tijd genomen",
        "tax": "Belasting",
        "round_off": "Afronden",
        "close": "Dichtbij",
        "help": "Helpen",
        "support": "Steun",
        "call": "Telefoongesprek",
        "message": "Bericht",
        "our_you_soon!": "Onze teamleden nemen spoedig contact met u op!",
        "invite_friend": "Invite Friend",
        "your_referral_code": "Uw verwijzingscode",
        "choose_one": "kies er een",
        "referral_count :": "Aantal verwijzingen:",
        "referral_amount:": "Verwijzingsbedrag:",
        "notification_manager": "Meldingsmanager",
        "you_any_notification": "Je hebt geen melding",
        "passbook": "Passbook",
        "no_wallet_history": "Geen portemonnee-geschiedenis",
        "amount": "Hoeveelheid",
        "balance": "Evenwicht :",
        "lost_my_item": "Mijn item verloren",
        "past_trip_details": "Eerdere reisdetails",
        "pay_via": "Betalen via",
        "comments": "Opmerkingen",
        "no_comments": "Geen reacties",
        "view_receipt": "Bekijk bon",
        "open": "OPEN",
        "payment_options": "Betalingsmogelijkheden",
        "cash": "CONTANT GELD",
        "by_cash": "Contant",
        "card": "Kaart",
        "add": "Toevoegen",
        "payStack": "PayStack",
        "profile": "Profiel",
        "phone_number": "Telefoonnummer",
        "looking_to_change_password": "Op zoek naar wachtwoord wijzigen",
        "save": "Opslaan",
        "setting": "Instelling",
        "favorites": "Favorieten",
        "home": "Huis",
        "work": "Werk",
        "choose_language": "Kies een taal",
        "upcoming_trip_details": "Aankomende reisdetails",
        "cancel_ride": "Rit annuleren",
        "wallet": "Portemonnee",
        "your_wallet_amount": "Uw Wallet-bedrag",
        "add_money": "Voeg geld toe",
        "add_amount": "Bedrag toevoegen",
        "please_enter_amount": "Vul a.u.b. bedrag in",
        "Please_enter_more_when_amount": "Vul a.u.b. meer dan 0 bedrag in",
        "your_trips": "Uw reizen",
        "no_past_Trips_found": "Geen eerdere reizen gevonden",
        "no_upcoming_trips_found": "Geen aankomende reizen gevonden",
        "cancel": "Annuleren",
        "add_card_for_payments": "Kaart toevoegen voor betalingen",
        "card_number": "Kaartnummer",
        "expiration_date": "vervaldatum",
        "add_card": "Voeg een kaart toe",
        "please_insert_valid_expiry_date": "Voer een geldige vervaldatum in",
        "change_password": "Verander wachtwoord",
        "current_password": "huidi wachtwoord",
        "chat": "Chatten",
        "loading...": "Bezig met laden...",
        "type_something_here": "Typ hier iets",
        "from_to": "bestemming invoeren",
        "where_to?": "Waarheen?",
        "apply_coupon": "gebruik coupon",
        "view_code": "Bekijk code",
        "request": "Verzoek",
        "rate_card": "Tariefkaart",
        "fare /": "Tarief /",
        "fare_type": "Tarieftype",
        "capacity": "Capaciteit",
        "schedule_a_ride": "Plan een rit",
        "choose_a_date": "Kies een datum",
        "please_select_date": "Selecteer datum a.u.b.",
        "please_select_time": "Selecteer tijd a.u.b.",
        "sos": "SOS",
        "otp:": "OTP: ",
        "cancel_trip": "Reis annuleren",
        "eta": "ETA",
        "share_status": "Deel status",
        "location_permissions_are_denied": "Locatierechten zijn geweigerd",
        "allow": "Toestaan",
        "kms": "km",
        "where_to": "Waarheen",
        "pick_from_map": "Kies uit kaart",
        "round_trip": "Rondvaart",
        "location_permissions_denied": "Locatierechten zijn geweigerd",
        "payment": "Betaling",
        "apply_coupan": "gebruik coupon",
        "cpD01": "CPD01",
        "10%_Off_Max_50": "10% korting Max korting is 50",
        "valid_Till_13,June_2021": "geldig t/m : 13 juni 2021",
        "view_Code": "Bekijk code",
        "case": "CONTANT GELD",
        "location_denied": "Locatierechten zijn geweigerd",
        "payments": "Betalingen",
        "offer": "Bieden",
        "settings": "Instellingen",
        "notification_manger": "Meldingsmanager",
        "share": "Deel",
        "invite_Friend": "Nodig een vriend uit",
        "logout": "Uitloggen",
        "choose_onew": "Kies er een",
        "hey_User": "Hey Check deze app, Mozlit-gebruiker",
        "use_wallet": "Portemonnee gebruiken",
      },
    };
  }
}
